### ISSUE TITLE
It's not clear how to receive Acks on the client side

### ISSUE THREAD

**Issue by derekwyatt** [lihaoyi/SprayWebSockets#16]
I can't see how the client can receive Acks.

I'm using this library as a client.  The TcpPipelineHandler actor (in Akka) holds my specific pipeline and brokers between my app and the socket (which is a spray web socket).  My pipeline has a backpressure buffer (from Akka) that requires Acks to be propagated back to the pipeline from the socket.

I have some code that bridges between a "standard looking" IO client and the web socket that looks something like this:

```
case Tcp.Write(bytes, ack) =>
    websocket ! Frame(...)
```

I need to ack back to the sender once the socket has completed its write, in order to ensure that my backpressure buffer does the right thing.  However, I don't know how to get an Ack back from the web socket.

For now I'm acking immediately but this, of course, isn't going to work because it's going to signal to the sender that he's good to send another write immediately, which is causing failures:

```
Failing write command because there is already another write in progress
```

Am I missing something or is this just not currently possible?

**Comment by sirthias** [comment]
Derek,
Jamie pointed me to this issue in an attempt to get you guys some support.
I have to admit that I've not yet had the time to look into @lihaoyi's websocket solution here.
Do you have the feeling that there is something that we can do from the spray side to get this problem resolved for you?

**Comment by lihaoyi** [comment]
I haven't touched this code in a while and don't really remember how any of
it works anymore =P I also haven't been using it myself and don't have the
time to investigate and re-familiarize myself with it, so I'm afraid you
guys will have to dig into the code and debug it yourself.

**Comment by derekwyatt** [comment]
Thanks guys (and sorry for the delay here... lots of work getting the beta going).

At the moment, I think I'm looking for some guidance.  Given what I've defined above, I believe we're losing data.  Our solution will retry, and eventually gets everything we need, but it's not exactly the best solution :)

It's simply not clear to me how we thread the flow-control through from the application, using Acks, to the WebSocket bridge I've written (the case statement above), into the WebSocket library, and then through Spray such that we can avoid the 'failing write' errors.

In the App I'm using a BackpressureBuffer and it really only works if the Acks make sense (i.e. are end-to-end complete) and I'm just not sure how to get it to work.

**Comment by sirthias** [comment]
Derek,
if your application is the one producing the data in the first place (rather than receiving them from some external entity at a rate you can't control) then that problem is "simply" to make sure that
1. all writes reaching the IO layer are ACKed writes and
2. establish a proper back-channel for ACKs through all layers

spray itself should do this, i.e. it should never send a second write before the ACK of the previous one has come back and it should always return application-level ACKs back to the application.
Whether @lihaoyi's code does this as well I don't know.

Unfortunately, as we can see here, the ACK-based approach is quite brittle in of itself, which is why for akka-http we'll move to a more robust architecture that has the backpressure channel built in at the core level. Then it will be impossible to mess this up. Until this is available though I'm afraid we'll have to patch our way through... :-/

**Comment by derekwyatt** [comment]
What we have looks like this:

```
Lots of 'clients' <--> my actor <--> TcpPipelineHandler with backpressure buffer <--> my actor <--> websocket <--> spray
```

I have no control over how fast the clients send things to the first actor, but the backpressure buffer in the TcpPipelineHandler is supposed to help with that, since it has an Akka BackpressureBuffer in the pipeline.

But what I can't seem to be able to is wire the acks, that the BackpressureBuffer is expecting, into spray.  I shouldn't ack the BackpressureBuffer until the write that went through the websocket / spray has been acked.

Is there any way to wire these acks together?  Forget the websocket guy for the moment... could I wire these together with spray alone?

**Comment by sirthias** [comment]
Ok, Derek, I see.
What client-side API level (connection-, host- or request-level) is the websocket logic using?
We have an open ticket that is related: https://github.com/spray/spray/issues/572

Currently, on the client-side, only the lowest-level (connection-level) API-level gives you full and proper (N)ACKing. I would assume that @lihaoyi's code uses the connections directly, so things should be good, but I wanted to confirm.

> But what I can't seem to be able to is wire the acks, that the BackpressureBuffer is expecting, into spray. I shouldn't ack the BackpressureBuffer until the write that went through the websocket / spray has been acked.
> 
> Is there any way to wire these acks together? Forget the websocket guy for the moment... could I wire these together with spray alone?

This shouldn't be hard.
Instead of

```
sprayLevelConnectionActor ! request
```

you simply say

```
sprayLevelConnectionActor ! request.withAck('myAck)
```

Then the sender will receive a `'myAck` message after the write has been successfully passed to the network.

**Comment by derekwyatt** [comment]
(Finally getting my head above water long enough to have a look at this again)

I'll dance around the websocket code and see what I can do.  At the moment, I believe it only allows for the sending of a Frame with no explicit Ack (or NoAck).  If all I have to do is add an API to make this possible and then plumb it together, that sounds pretty doable.

**Comment by sirthias** [comment]
Ok, great.
Let me know if you think that there is anything we can do from the spray-side you support your efforts.

**Comment by derekwyatt** [comment]
This was just taking up too much of my time so I decided to go a different way.  In the end, I built a simple WebSocket client without Spray.  It's not pretty, but it does what I need it to do for the moment and I can move back on to the other stuff that needs doing.  I may be able to come back to this at a later date.

**Comment by sirthias** [comment]
Ok, thanks for the update, Derek!
Of course we still have websockets on our agenda and they will definitely come.
However, currently we are completely swamped with the move into akka-http and onto akka-streams.
(I assume you are already following https://github.com/spray/spray/issues/134)
